name: Checkout Other Repo's Latest Commit

on:
  # https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow
  workflow_dispatch:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch
  repository_dispatch:
    types: [ build_npm ]

jobs:
  get-repo-ref:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for getting latest commit
        uses: actions/checkout@v4
        with:
          repository: lwtlab/lwt-core
          token: ${{ secrets.GH_PAT }}
      - name: Setup variable REPO_REF (for checking out code), REPO_SHA (short SHA for display) and REPO_TAG (for display)
        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-of-writing-an-environment-variable-to-github_env
        run: |
          if [ -z "${{ github.event.client_payload.ref }}" ]; then
            echo "REPO_REF=$(git rev-parse HEAD)" >> $GITHUB_ENV
            echo "REPO_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
            echo "REPO_TAG=" >> $GITHUB_ENV
          else
            echo "REPO_REF=${{ github.event.client_payload.ref }}" >> $GITHUB_ENV
            echo "REPO_SHA=${{ github.event.client_payload.sha }}" >> $GITHUB_ENV
            echo "REPO_TAG=${{ github.event.client_payload.tag }}" >> $GITHUB_ENV
          fi
      - name: DEBUG variable REPO_REF, REPO_SHA and REPO_TAG
        run: echo "$REPO_REF, $REPO_SHA, $REPO_TAG"
  build:
    runs-on: ubuntu-latest
    needs:
      - get-repo-ref
    steps:
      - name: DEBUG variable REPO_REF, REPO_SHA and REPO_TAG
        run: echo "$REPO_REF, $REPO_SHA, $REPO_TAG"
      - name: DEBUG env.REPO_REF, REPO_SHA and REPO_TAG
        run: echo "${{ env.REPO_REF }}, ${{ env.REPO_SHA }}, ${{ env.REPO_TAG }}"
