name: Checkout Other Repo's Latest Commit

on:
  # https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow
  workflow_dispatch:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch
  repository_dispatch:
    types: [ build_npm ]

jobs:
  checkout-and-retrieve-sha:
    runs-on: ubuntu-latest
    steps:
      - name: Run a command
        run: |
          echo "The event payload is: ${{ github.event.client_payload }}"
      - uses: actions/checkout@v3
        with:
          repository: lwtlab/lwt-core
          token: ${{ secrets.GH_PAT }}
          submodules: true

      - name: Get SHA of the latest commit
        id: latest-commit-sha
        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-of-writing-an-environment-variable-to-github_env
        run: |
          LATEST_SHA=$(git rev-parse --short HEAD)
          echo "Latest commit SHA is $LATEST_SHA"
          echo "REPO_REF=$LATEST_SHA" >> "$GITHUB_ENV"

      - name: Print the latest commit SHA
        run: echo "The latest commit SHA is $REPO_REF"
